// Code generated by meshRPC. DO NOT EDIT.
// All changes must be done in custom client that should either embed or wrap this.

package greeter

import (
	"bytes"
	"encoding/json"
	"io"

	"github.com/gin-gonic/gin"
)

type RPCHandler interface {
	Greet(ctx *gin.Context)
	SendPostcard(ctx *gin.Context)
}

var RPCHandlerSpec RPCHandler = &rpcHandler{}

type RPCHandlerOptions struct {
}

func checkRPCHandlerOptions(opt *RPCHandlerOptions) *RPCHandlerOptions {
	if opt == nil {
		opt = &RPCHandlerOptions{}
	}
	return opt
}

func NewRPCHandler(
	svc Service,
	opt *RPCHandlerOptions,
) RPCHandler {
	return &rpcHandler{
		opt: checkRPCHandlerOptions(opt),
		svc: svc,
	}
}

type rpcHandler struct {
	svc Service
	opt *RPCHandlerOptions
}

type GreetRequest struct {
	Name string `json:"name,omitempty"`
}

type GreetResponse struct {
	ErrorResponse
	Message string `json:"message,omitempty"`
}

func (_handler *rpcHandler) Greet(_ctx *gin.Context) {
	// TODO: Report Stats + Timing

	var _req GreetRequest
	_decoder := json.NewDecoder(_ctx.Request.Body)
	defer _ctx.Request.Body.Close()
	_err := _decoder.Decode(&_req)
	if _err != nil {
		// TODO: Report Error

		_data, _ := json.Marshal(&GreetResponse{
			ErrorResponse: ErrorResponse{
				Error: _err.Error(),
			},
		})
		_ctx.Status(400)
		// TODO: Report Stats
		_, _ = io.Copy(_ctx.Writer, bytes.NewReader(_data))
		return
	}
	var _resp GreetResponse
	_resp.Message, _err = _handler.svc.Greet(_req.Name)
	if _err != nil {
		// TODO: Report Error

		_data, _ := json.Marshal(&GreetResponse{
			ErrorResponse: ErrorResponse{
				Error: _err.Error(),
			},
		})
		_ctx.Status(400)
		// TODO: Report Stats
		_, _ = io.Copy(_ctx.Writer, bytes.NewReader(_data))
		return
	}

	_data, _ := json.Marshal(&_resp)
	_ctx.Status(200)
	// TODO: Report Stats
	_, _ = io.Copy(_ctx.Writer, bytes.NewReader(_data))
	return
}

type SendPostcardRequest struct {
	Card *Postcard `json:"card,omitempty"`
}

type SendPostcardResponse struct {
	ErrorResponse
}

func (_handler *rpcHandler) SendPostcard(_ctx *gin.Context) {
	// TODO: Report Stats + Timing

	var _req SendPostcardRequest
	_decoder := json.NewDecoder(_ctx.Request.Body)
	defer _ctx.Request.Body.Close()
	_err := _decoder.Decode(&_req)
	if _err != nil {
		// TODO: Report Error

		_data, _ := json.Marshal(&SendPostcardResponse{
			ErrorResponse: ErrorResponse{
				Error: _err.Error(),
			},
		})
		_ctx.Status(400)
		// TODO: Report Stats
		_, _ = io.Copy(_ctx.Writer, bytes.NewReader(_data))
		return
	}
	var _resp SendPostcardResponse
	_err = _handler.svc.SendPostcard(_req.Card)
	if _err != nil {
		// TODO: Report Error

		_data, _ := json.Marshal(&SendPostcardResponse{
			ErrorResponse: ErrorResponse{
				Error: _err.Error(),
			},
		})
		_ctx.Status(400)
		// TODO: Report Stats
		_, _ = io.Copy(_ctx.Writer, bytes.NewReader(_data))
		return
	}

	_data, _ := json.Marshal(&_resp)
	_ctx.Status(200)
	// TODO: Report Stats
	_, _ = io.Copy(_ctx.Writer, bytes.NewReader(_data))
	return
}

var rpcHandlerMethodsMap = map[string][]string{
	"*": []string{
		"POST",
	},
}

func (_ *rpcHandler) HTTPMethodsMap() map[string][]string {
	return rpcHandlerMethodsMap
}

type ErrorResponse struct {
	Error string `json:"error"`
}
